# Site
name: '快知区块链 Kchain.news'
description: ''
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
#disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    fangjun:
      name:           方军
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "方军，著有《平台时代》《区块链超入门》"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    kfriends:
      name:           快链的朋友们
      site:           https://www.wowthemes.net
      avatar:
      bio:            "快链朋友们"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           快知区块链
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "快知区块链研究与出品"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

collections:
  block100:
    output: true
  contracts:
    output: true

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]